#!/bin/bash

INSTALLER_USER=$(stat -f '%Su' $HOME)
[ -n "${USER}" ] && USER=${INSTALLER_USER}

LOG_FILE=/tmp/postinstall.log

# Close standard output file descriptor
exec 1<&-
# Close standard error file descriptor
exec 2<&-

# Open standard output as $LOG_FILE file for read and write.
exec 1<>$LOG_FILE

# Redirect standard error to standard output
exec 2>&1

APP_NAME=Cellframe-Dashboard
DAP_PREFIX=$HOME/Applications/Cellframe.app/Contents/Resources
SERVICE=com.demlabs."$APP_NAME"Service
NODE=com.demlabs.cellframe-node

set -x
sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
sudo killall -HUP mDNSResponder

EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/Resources

mkdir -p $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX

for filename in $(find $DAP_PREFIX | grep -v bugreport); do
    if [ -d $filename ]; then
        chmod 0775 $filename || true
    else
        chmod 0664 $filename || true
    fi
done

wd=$(pwd)
cd $EXEC_PREFIX/../MacOS

for filename in $(ls . | grep -v '.'); do
	if [ -L $filename ] && [ ! -e $filename ]; then
		strip -u -r $filename
	fi
done

sudo chmod +x $EXEC_PREFIX/create_configs.sh
sudo chmod +x $EXEC_PREFIX/create_configs_from_tpl.sh

$EXEC_PREFIX/create_configs.sh

 mkdir -p $HOME/Library/LaunchAgents

sudo chown $USER /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist
sudo chmod 644 /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist


sudo chown $USER /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist
sudo chmod 644 /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist

 sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist $HOME/Library/LaunchAgents/$SERVICE.plist
 sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist $HOME/Library/LaunchAgents/$NODE.plist
 sudo -u $USER launchctl load -w $HOME/Library/LaunchAgents/$NODE.plist
 sudo -u $USER launchctl load -w $HOME/Library/LaunchAgents/$SERVICE.plist

 rm -r $HOME/Applications/"$APP_NAME".app/Contents/Resources/var/lib/global_db/gdb-cdb/

 sudo -u $USER launchctl start $NODE
 sudo -u $USER launchctl start $SERVICE

sudo rm $EXEC_PREFIX/*.sh
sudo rm /Applications/$APP_NAME.plist
sudo rm /Applications/Cellframe.app


echo "node agent: $(launchctl list | grep cell)" > /tmp/cellframe-dashboard_install_logs.txt
echo "service agent: $(launchctl list | grep cell)" > /tmp/cellframe-dashboard_install_logs.txt

cd $wd
