#!/bin/bash

APP_NAME=Cellframe-Dashboard
DAP_PREFIX=/Users/$USER/Applications/Cellframe.app/Contents/Resources
set -x
sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
sudo killall -HUP mDNSResponder

EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/MacOS
SERVICE=com.demlabs."$APP_NAME"Service.plist
NODE=com.demlabs.cellframe-node.plist

mkdir -p $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX

for filename in $(find $DAP_PREFIX | grep -v bugreport); do
    if [ -d $filename ]; then
        chmod 0775 $filename || true
    else
        chmod 0664 $filename || true
    fi
done

wd=$(pwd)
cd $EXEC_PREFIX

sudo chmod +x $EXEC_PREFIX/create_configs.sh
sudo chmod +x $EXEC_PREFIX/create_configs_from_tpl.sh

$EXEC_PREFIX/create_configs.sh || { echo "not create config $?" >> /tmp/cellframe-dashboard_error.txt; exit $?; }

rm $EXEC_PREFIX/*.sh

for filename in $(ls . | grep -v '.'); do
	if [ -L $filename ] && [ ! -e $filename ]; then
		strip -u -r $filename
	fi
done

cd $wd

echo $SERVICE || exit $?
sudo launchctl stop $SERVICE || true
sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE || exit $?

echo $NODE || exit $?
sudo launchctl stop $NODE || true
sudo launchctl unload -w /Library/LaunchDaemons/$NODE || exit $?

sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE /Library/LaunchDaemons/$SERVICE || exit $?
sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE /Library/LaunchDaemons/$NODE || exit $?

sudo chown root /Library/LaunchDaemons/$SERVICE || exit $?
sudo chmod 600 /Library/LaunchDaemons/$SERVICE || exit $?
sudo chown root /Library/LaunchDaemons/$NODE || exit $?
sudo chmod 600 /Library/LaunchDaemons/$NODE || exit $?
sudo launchctl load -w /Library/LaunchDaemons/$NODE || exit $?
sudo launchctl load -w /Library/LaunchDaemons/$SERVICE || exit $?
# [ ! -e /Library/LaunchDaemons/cleanup ] && sudo cp -r /Applications/"$APP_NAME".app/Contents/resources/cleanup /Library/LaunchDaemons/
# sudo chown -R root:wheel /Library/LaunchDaemons/cleanup
# sudo ln -sf /Library/LaunchDaemons/cleanup/com.demlabs.cleanup.plist /Library/LaunchDaemons/com.demlabs.cleanup.plist
# sudo chmod 600 /Library/LaunchDaemons/com.demlabs.cleanup.plist
# sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.cleanup.plist
# sudo chmod 500 /Library/LaunchDaemons/cleanup/cleanup.sh



sudo launchctl start $NODE || exit $?
sudo launchctl start $SERVICE || exit $?

