#!/bin/bash

APP_NAME=Cellframe-Dashboard
DAP_PREFIX=/Users/$USER/Applications/Cellframe.app/Contents/Resources
set -x
sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
sudo killall -HUP mDNSResponder

EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/MacOS
SERVICE=com.demlabs."$APP_NAME"Service
NODE=com.demlabs.cellframe-node

mkdir -p $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
sudo mv -f /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX

for filename in $(find $DAP_PREFIX | grep -v bugreport); do
    if [ -d $filename ]; then
        chmod 0775 $filename || true
    else
        chmod 0664 $filename || true
    fi
done

wd=$(pwd)
cd $EXEC_PREFIX

sudo chmod +x $EXEC_PREFIX/create_configs.sh
sudo chmod +x $EXEC_PREFIX/create_configs_from_tpl.sh

$EXEC_PREFIX/create_configs.sh 2>> /tmp/cellframe-dashboard_error.txt || { error=$?; echo "not create configs $error" >> /tmp/cellframe-dashboard_error.txt; exit $error; }

rm $EXEC_PREFIX/*.sh

for filename in $(ls . | grep -v '.'); do
	if [ -L $filename ] && [ ! -e $filename ]; then
		strip -u -r $filename
	fi
done

cd $wd

[ ! -e /Library/LaunchDaemons/cleanup ] && sudo cp -r /Applications/"$APP_NAME".app/Contents/resources/cleanup /Library/LaunchDaemons/
 sudo chown -R root:wheel /Library/LaunchDaemons/cleanup
 sudo ln -sf /Library/LaunchDaemons/cleanup/com.demlabs.cleanup.plist /Library/LaunchDaemons/com.demlabs.cleanup.plist
 sudo chmod 600 /Library/LaunchDaemons/com.demlabs.cleanup.plist
 sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.cleanup.plist
 sudo chmod 500 /Library/LaunchDaemons/cleanup/cleanup.sh

echo $SERVICE
sudo launchctl stop $SERVICE
sudo launchctl unload -w ~/Library/LaunchAgents/$SERVICE.plist

echo $NODE || exit $?
sudo launchctl stop $NODE
sudo launchctl unload -w ~/Library/LaunchAgents/$NODE

sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist ~/Library/LaunchAgents/$SERVICE.plist
sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist ~/Library/LaunchAgents/$NODE.plist

# sudo chown root /Library/LaunchDaemons/$SERVICE.plist
# sudo chmod 600 /Library/LaunchDaemons/$SERVICE.plist
# sudo chown root /Library/LaunchDaemons/$NODE.plist
# sudo chmod 600 /Library/LaunchDaemons/$NODE.plist
sudo launchctl load -w /Library/LaunchDaemons/$NODE.plist
sudo launchctl load -w /Library/LaunchDaemons/$SERVICE.plist




launchctl start $NODE || true
launchctl start $SERVICE || true

