#!/bin/bash

APP_NAME=CellFrameDashboard
DAP_PREFIX=/Users/$USER/Applications/Cellframe.app/Contents/Resources
set -x
sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
sudo killall -HUP mDNSResponder

EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/MacOS
SERVICE=com.demlabs."$APP_NAME"Service.plist
NODE=com.demlabs.cellframe-node.plist

mkdir -p $DAP_PREFIX
cp -rf /Applications/$APP_NAME.app/Contents/Resources/etc $DAP_PREFIX
cp -rf /Applications/$APP_NAME.app/Contents/Resources/share $DAP_PREFIX

for filename in $(find $DAP_PREFIX | grep -v bugreport); do
    if [ -d $filename ]; then
        chmod 0775 $filename || true
    else
        chmod 0664 $filename || true
    fi
done

wd=$(pwd)
cd $EXEC_PREFIX

chmod +x $EXEC_PREFIX/create_configs.sh
$EXEC_PREFIX/create_configs.sh

for filename in $(ls . | grep -v '.'); do
	if [ -L $filename ] && [ ! -e $filename ]; then
		strip -u -r $filename
	fi
done

cd $wd

echo $SERVICE
sudo launchctl stop $SERVICE
sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE

echo $NODE
sudo launchctl stop $NODE
sudo launchctl unload -w /Library/LaunchDaemons/$NODE

sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE /Library/LaunchDaemons/$SERVICE
sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE /Library/LaunchDaemons/$NODE

sudo chown root /Library/LaunchDaemons/$SERVICE
sudo chmod 600 /Library/LaunchDaemons/$SERVICE
sudo chown root /Library/LaunchDaemons/$NODE
sudo chmod 600 /Library/LaunchDaemons/$NODE
sudo launchctl load -w /Library/LaunchDaemons/$SERVICE
sudo launchctl load -w /Library/LaunchDaemons/$NODE
[ ! -e /Library/LaunchDaemons/cleanup ] && sudo cp -r /Applications/"$APP_NAME".app/Contents/resources/cleanup /Library/LaunchDaemons/
sudo chown -R root:wheel /Library/LaunchDaemons/cleanup
sudo ln -sf /Library/LaunchDaemons/cleanup/com.demlabs.cleanup.plist /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo chmod 600 /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo chmod 500 /Library/LaunchDaemons/cleanup/cleanup.sh

#sudo mkdir -p /Users/.DapVPN
#touch /Users/.DapVPN/dap_brands
#sudo cp -f /Applications/DiveVPN.app/Contents/Resources/*.sh /Users/.DapVPN/
#sudo chown root /Users/.DapVPN/*.sh
#sudo chmod 500 /Users/.DapVPN/*.sh
#sudo cp -f /Applications/DiveVPN.app/Contents/Resources/com.demlabs.DiveVPN-watchdog.plist /Library/LaunchDaemons
#sudo chown root /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist
#sudo chmod 600 /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist 
#sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist #It is self-deleting thing


sudo launchctl start $NODE
sudo launchctl start $SERVICE
#sudo launchctl start -w com.demlabs.DiveVPN-watchdog.plist

set +x
