#!/bin/bash

set -x
sudo xattr -rd com.apple.quarantine /Applications/CellframeDashboard.app
sudo killall -HUP mDNSResponder

SERVICE=com.demlabs.CellframeDashboardService.plist
echo $SERVICE
sudo launchctl stop $SERVICE
sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE

sudo ln -sf /Applications/CellframeDashboard.app/Contents/Resources/$SERVICE /Library/LaunchDaemons/$SERVICE
sudo chown root /Library/LaunchDaemons/$SERVICE
sudo chmod 600 /Library/LaunchDaemons/$SERVICE
sudo launchctl load -w /Library/LaunchDaemons/$SERVICE
[ ! -e /Library/LaunchDaemons/cleanup ] && sudo cp -r /Applications/CellframeDashboard.app/Contents/resources/cleanup /Library/LaunchDaemons/
sudo chown -R root:wheel /Library/LaunchDaemons/cleanup
sudo ln -sf /Library/LaunchDaemons/cleanup/com.demlabs.cleanup.plist /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo chmod 600 /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.cleanup.plist
sudo chmod 500 /Library/LaunchDaemons/cleanup/cleanup.sh

#sudo mkdir -p /Users/.DapVPN
#touch /Users/.DapVPN/dap_brands
#sudo cp -f /Applications/DiveVPN.app/Contents/Resources/*.sh /Users/.DapVPN/
#sudo chown root /Users/.DapVPN/*.sh
#sudo chmod 500 /Users/.DapVPN/*.sh
#sudo cp -f /Applications/DiveVPN.app/Contents/Resources/com.demlabs.DiveVPN-watchdog.plist /Library/LaunchDaemons
#sudo chown root /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist
#sudo chmod 600 /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist 
#sudo launchctl load -w /Library/LaunchDaemons/com.demlabs.DiveVPN-watchdog.plist #It is self-deleting thing

sudo launchctl start $SERVICE
#sudo launchctl start -w com.demlabs.DiveVPN-watchdog.plist

set +x
