#!/bin/bash

echo "Installing time!" >> /tmp/debug_vpn.txt

BRAND=CellFrameDashboard

RET=0
echo "Installation logs" > /tmp/CellFrameDashboard_Install_Logs.txt

echo "Gui_check" >> /tmp/debug_dashboard.txt
if pgrep -x "CellFrameDashboard" > /dev/null
then
    	echo "Gui is Running" >> /tmp/CellFrameDashboard_Install_Logs.txt
    	./cmdAlert.app/Contents/MacOS/cmdAlert
	RET=$?
else
    	echo "Gui Stopped" >> /tmp/CellFrameDashboard_Install_Logs.txt
fi

echo "RET from asking user = $RET" >> /tmp/CellFrameDashboard_Install_Logs.txt
if [ "$RET" -eq "0" ]; then
	echo "Continue install" >> /tmp/CellFrameDashboard_Install_Logs.txt
elif [ "$RET" -eq "1" ]; then
	echo "Stop install" >> /tmp/CellFrameDashboard_Install_Logs.txt
	exit 1
fi


#### Kill all opened CellframeDashboard gui clients
GuiPIDs=$(pgrep -x "CellframeDashboard")
while read -r GuiPID; do
    	echo "... $GuiPID ..." >> /tmp/CellFrameDashboard_Install_Logs.txt
	if [ "$GuiPID" != "" ]; then
		echo "CellFrameDashboard is set! Kill It!!!" >> /tmp/CellFrameDashboard_Install_Logs.txt
		sudo kill $GuiPID
	fi
done <<< "$GuiPIDs"

echo "unloading the weirdo deps" >> /tmp/debug_dashboard.txt


[ -e /Library/LaunchDaemons/com.demlabs.CellFrameDashboardService.plist ] && sudo launchctl unload -w /Library/LaunchDaemons/com.demlabs.CellframeDashboardService.plist
[ -e /Library/LaunchDaemons/com.demlabs.cellframe-node.plist ] && sudo launchctl unload -w /Library/LaunchDaemons/com.demlabs.cellframe-node.plist

#udo rm -fr /Applications/${BRAND}.app



#delete CellframeDashboards from com.apple.dock.plist
echo "path to dock /Users/$USER/Library/Preferences/com.apple.dock.plist" >> /tmp/CellFrameDashboard_Install_Logs.txt
dockApps=$(defaults read /Users/$USER/Library/Preferences/com.apple.dock.plist persistent-apps | nl | grep file-label | awk '/CellframeDashboard/  {print NR}')
cnt=1
while read -r app; do
	app=$[$app-$cnt]
	cnt=$[$cnt+1]
	if [ "$app" -ne "-1" ]; then
		echo "app in dock exists" >> /tmp/CellFrameDashboard_Install_Logs.txt
		sudo -u $USER /usr/libexec/PlistBuddy -c "Delete persistent-apps:$app" /Users/$USER/Library/Preferences/com.apple.dock.plist
	else
		echo "app in dock don't exists" >> /tmp/CellFrameDashboard_Install_Logs.txt
	fi
done <<< "$dockApps"
osascript -e 'delay 2' -e 'tell Application "Dock"' -e 'quit' -e 'end tell'
osascript -e 'delay 2' -e 'tell Application "Dock"' -e 'quit' -e 'end tell'
exit 0

echo "cleanup done" >> /tmp/debug_dashboard.txt
